FROM python:3.8.10
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="jubeaz"

ARG PYINSTALLER_VERSION=6.6.0

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY docker/entrypoint-linux.sh /entrypoint.sh
RUN apt-get update && apt-get upgrade -y
RUN apt-get install curl build-essential gcc make rustc -y
RUN python3 -m pip install --upgrade pip
RUN pip3 install \
        pyinstaller==$PYINSTALLER_VERSION \
    && pip3 cache purge \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]